<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <NupkgToolPath>$(RepositoryRoot)src\Packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform\tools\</NupkgToolPath>
        <LocalRoslyn46FolderName>Roslyn46</LocalRoslyn46FolderName>
        <LocalRoslyn472FolderName>Roslyn472</LocalRoslyn472FolderName>
    </PropertyGroup>
</Project>
